import * as pc from 'playcanvas';
import { useCallback, useEffect, useRef, useState } from 'react';

import {
  Graph,
  mangleVar,
  SamplerCubeNode,
  TextureNode,
  evaluateNode,
} from '@core/graph';
import {
  EngineContext,
  collectInitialEvaluatedGraphProperties,
} from '@core/engine';
import styles from '../../editor/styles/editor.module.css';

import { usePrevious } from '../../editor/hooks/usePrevious';
import { UICompileGraphResult } from '../../editor/uICompileGraphResult';
import { useSize } from '../../editor/hooks/useSize';

import {
  defaultPropertySetting,
  physicalDefaultProperties,
  playengine,
} from '@core/plugins/playcanvas/playengine';
import { usePlayCanvas } from './usePlayCanvas';

export type PreviewLight = 'point' | '3point' | 'spot';

let mIdx = 0;
let id = () => mIdx++;

const log = (...args: any[]) =>
  console.log.call(console, '\x1b[36m(pc.component)\x1b[0m', ...args);

// Intercept console errors, which is the only way to get playcanvas shader
// error logs
const consoleError = console.error;
let callback: Function;
console.error = (...args: any[]) => {
  if (callback) {
    callback(...args);
  }
  return consoleError.apply(console, args);
};

const makeLightHelper = () => {
  const entity = new pc.Entity('render');
  entity.addComponent('model', {
    type: 'box',
  });
  entity.setLocalScale(0.1, 0.1, 0.1);
  entity.rotate(45, 45, 0);
  entity.model!.model.generateWireframe();
  entity.model!.meshInstances.forEach((mi) => {
    mi.renderStyle = 1;
    mi.material = mi.material.clone();
    // @ts-ignore lol
    mi.material.diffuse.set(0, 0, 0, 0);
    // @ts-ignore lol
    mi.material.specular.set(0, 0, 0, 0);
    // @ts-ignore lol
    mi.material.shininess = 0;
    // @ts-ignore lol
    mi.material.emissive.set(1, 1, 1, 1);
    mi.material.update();
  });
  return entity;
};

/**
 * MONKEYPATCH WARNING! We need to overwrite the GLSL generated by PlayCanvas in
 * their materials. This function overwrites the core generateShaderDefinition()
 * call, and lets this component define an intercept function.
 */
const RUNTIME_CHUNK_HACK_NAME = 'runtimeHackSource';
let hackShaderDefinition: (event: {
  userMaterialId: string;
  shaderPassInfo: any;
  definition: any;
}) => void;

const loadAsset = (
  app: pc.Application,
  name: string,
  url: string
): Promise<pc.Asset> =>
  new Promise((resolve) => {
    const cubemapAsset = new pc.Asset(
      name,
      'cubemap',
      {
        url,
      },
      {}
    );

    app.assets.add(cubemapAsset);
    app.assets.load(cubemapAsset);
    cubemapAsset.ready(() => resolve(cubemapAsset));
  });

const buildTextureLoader =
  (app: pc.Application) =>
  async (path: string): Promise<pc.Texture> =>
    new Promise((resolve) => {
      const image = new Image();
      image.crossOrigin = 'anonymous';
      const texture = new pc.Texture(app.graphicsDevice, { name: path });
      image.onload = () => {
        texture.setSource(image);
        resolve(texture);
      };
      image.src = path;
    });

type AnyFn = (...args: any) => any;
type PlayCanvasComponentProps = {
  compile: AnyFn;
  compileResult: UICompileGraphResult | undefined;
  graph: Graph;
  lights: PreviewLight;
  animatedLights: boolean;
  setAnimatedLights: AnyFn;
  previewObject: string;
  setCtx: (ctx: EngineContext) => void;
  setGlResult: AnyFn;
  setLights: AnyFn;
  setPreviewObject: AnyFn;
  showHelpers: boolean;
  setShowHelpers: AnyFn;
  bg: string | undefined;
  setBg: AnyFn;
  width: number;
  height: number;
  assetPrefix: string;
};
const PlayCanvasComponent: React.FC<PlayCanvasComponentProps> = ({
  compile,
  compileResult,
  graph,
  lights,
  setLights,
  animatedLights,
  setAnimatedLights,
  previewObject,
  setCtx,
  setGlResult,
  setPreviewObject,
  bg,
  setBg,
  showHelpers,
  setShowHelpers,
  width,
  height,
  assetPrefix,
}) => {
  const path = useCallback((src: string) => assetPrefix + src, [assetPrefix]);
  const sceneWrapper = useRef<HTMLDivElement>(null);
  const size = useSize(sceneWrapper);

  useEffect(() => {
    callback = (msg: string) => {
      if (msg.toString().startsWith('Failed to compile')) {
        const type = (msg.match(/compile (\w+)/) as string[])[1];
        const err = msg.replace(/.*shader:\n+/m, '').replace(/\n[\s\S]*/m, '');
        setGlResult({
          fragError: type === 'fragment' ? err : null,
          vertError: type === 'vertex' ? err : null,
          programError: '',
        });
      }
    };
  }, [setGlResult]);

  const { camera, canvas, pcDomRef, app, sceneData, loadingMaterial } =
    usePlayCanvas((deltaTime) => {
      const { mesh } = sceneData;
      const meshInstance = mesh?.render?.meshInstances?.[0];
      const { material: mMaterial } = meshInstance || {};
      const material = mMaterial as pc.StandardMaterial;
      if (!mesh || !meshInstance || !material) {
        return;
      }

      material.setParameter('time', performance.now() * 0.001);

      // Note the uniforms are updated here every frame, but also instantiated
      // in this component at RawShaderMaterial creation time. There might be
      // some logic duplication to worry about.
      if (textures && compileResult?.dataInputs && material) {
        Object.entries(compileResult.dataInputs).forEach(([nodeId, inputs]) => {
          const node = graph.nodes.find(({ id }) => id === nodeId);
          if (!node) {
            console.warn(
              'While populating uniforms, no node was found from dataInputs',
              { nodeId, dataInputs: compileResult.dataInputs, graph }
            );
            return;
          }
          inputs.forEach((input) => {
            const edge = graph.edges.find(
              ({ to, input: i }) => to === nodeId && i === input.id
            );
            if (edge) {
              const fromNode = graph.nodes.find(({ id }) => id === edge.from);
              // In the case where a node has been deleted from the graph,
              // dataInputs won't have been udpated until a recompile completes
              if (!fromNode) {
                return;
              }

              let value;
              // THIS DUPLICATES OTHER LINE
              try {
                value = evaluateNode(playengine, graph, fromNode);
              } catch (err) {
                console.warn(
                  `Tried to evaluate a non-data node! ${input.displayName} on ${node.name}`
                );
                return;
              }
              let newValue = value;
              if (fromNode.type === 'texture') {
                // THIS DUPLICATES OTHER LINE, used for runtime uniform setting
                newValue = textures[(fromNode as TextureNode).value];
                // console.log('setting texture', newValue, 'from', fromNode);
              }
              if (fromNode.type === 'samplerCube') {
                newValue = textures[(fromNode as SamplerCubeNode).value];
              }

              if (input.type === 'property' && input.property) {
                // @ts-ignore
                material[input.property] = newValue;
              } else {
                // TODO: This doesn't work for engine variables because
                // those aren't suffixed
                const name = mangleVar(input.displayName, playengine, node);
                material.setParameter(name, newValue);
                meshInstance.setParameter(name, newValue);
              }
            }
          });
        });

        material.update();
      }

      const { lights: lightMeshes } = sceneData;
      const time = Date.now();
      if (animatedLights) {
        if (lights === 'point') {
          const light = lightMeshes[0];
          light.setPosition(
            1.0 * Math.sin(time * 0.001),
            1.0 * Math.cos(time * 0.001),
            1.0
          );
          if (showHelpers) {
            const p = light.getPosition();
            lightMeshes[1].setPosition(p.x, p.y, p.z);
          }
        } else if (lights === '3point') {
          const group = lightMeshes[0];
          group.rotate(deltaTime * 20.0, deltaTime * 20.0, deltaTime * 20.0);
        }
      }
    });

  const [textures, setTextures] = useState<
    Record<string, pc.Texture | pc.Asset | null> | undefined
  >();
  useEffect(() => {
    const load = async () => {
      const textureLoader = buildTextureLoader(app);
      // Logging to check if this happens more than once
      log('🔥 Loading Playcanvas textures');
      setTextures({
        explosion: await textureLoader(path('/explosion.png')),
        'grayscale-noise': await textureLoader(path('/grayscale-noise.png')),
        threeTone: await textureLoader(path('/3tone.jpg')),
        brick: await textureLoader(path('/bricks.jpeg')),
        brickNormal: await textureLoader(path('/bricknormal.jpeg')),
        pebbles: await textureLoader(path('/Big_pebbles_pxr128.jpeg')),
        pebblesNormal: await textureLoader(
          path('/Big_pebbles_pxr128_normal.jpeg')
        ),
        pebblesBump: await textureLoader(path('/Big_pebbles_pxr128_bmp.jpeg')),
        pondCubeMap: null,
        cityCourtYard: await loadAsset(
          app,
          'city',
          path('/envmaps/citycourtyard.dds')
        ),
        warehouseEnvTexture: await loadAsset(
          app,
          'city',
          path('/envmaps/room.hdr')
        ),
      });
    };
    load();
  }, [path, app]);

  useEffect(() => {
    app.graphicsDevice.on('shader:generate', (info) => {
      hackShaderDefinition && hackShaderDefinition(info);
      return () => {
        app.graphicsDevice.off('shader:generate');
      };
    });
  }, [app, textures]);

  const [ctx] = useState<EngineContext>(() => {
    return {
      engine: 'playcanvas',
      runtime: {
        sceneData,
        // i'm not intentionally putting some things on scenedata and others on
        // runtime, it's just hacking to test out playcanvas
        app,
        textures,
        cache: { nodes: {}, data: {} },
      },
      nodes: {},
      debuggingNonsense: {},
    };
  });

  const prevLights = usePrevious(lights);
  const previousShowHelpers = usePrevious(showHelpers);
  useEffect(() => {
    if (
      (prevLights === lights && previousShowHelpers === showHelpers) ||
      (prevLights === undefined && sceneData.lights.length)
    ) {
      return;
    }
    sceneData.lights.forEach((light) => light.destroy());

    if (lights === 'point') {
      const pointLight = new pc.Entity('light');
      pointLight.addComponent('light', {
        type: 'omni',
        color: new pc.Color(1, 1, 1),
        range: 10,
      });
      pointLight.setPosition(0, 0, 3);
      sceneData.lights = [pointLight];

      if (showHelpers) {
        sceneData.lights.push(makeLightHelper());
      }
    } else if (lights === '3point') {
      const group = new pc.Entity('group');

      const light1 = new pc.Entity('light');
      light1.addComponent('light', {
        type: 'omni',
        color: new pc.Color(1, 1, 1),
        range: 10,
      });
      light1.setPosition(2, -2, 0);

      const light2 = new pc.Entity('light');
      light2.addComponent('light', {
        type: 'omni',
        color: new pc.Color(1, 1, 1),
        range: 10,
      });
      light2.setPosition(-1, 2, 1);

      const light3 = new pc.Entity('light');
      light3.addComponent('light', {
        type: 'omni',
        color: new pc.Color(1, 1, 1),
        range: 10,
      });
      light3.setPosition(-1, -2, -2);

      let lights = [light1, light2, light3];

      if (showHelpers) {
        const h1 = makeLightHelper();
        h1.setPosition(light1.getPosition());
        const h2 = makeLightHelper();
        h2.setPosition(light2.getPosition());
        const h3 = makeLightHelper();
        h3.setPosition(light3.getPosition());
        lights = lights.concat(h1, h2, h3);
      }
      lights.forEach((light) => {
        group.addChild(light);
      });

      sceneData.lights = [group];
    } else if (lights === 'spot') {
      const spot1 = new pc.Entity();
      spot1.addComponent('light', {
        type: 'spot',
        // new BABYLON.Vector3(0, 0, 2),
        // new BABYLON.Vector3(0, 0, -1),
      });
      spot1.setPosition(0, 0, 2);
      // spot1.diffuse = new BABYLON.Color3(0, 1, 0);
      // spot1.specular = new BABYLON.Color3(0, 1, 0);

      const spot2 = new pc.Entity();
      spot2.addComponent('light', {
        type: 'spot',
        // new BABYLON.Vector3(0, 0, 2),
        // new BABYLON.Vector3(0, 0, -1),
      });
      spot2.setPosition(0, 0, 2);
      // spot2.diffuse = new BABYLON.Color3(1, 0, 0);
      // spot2.specular = new BABYLON.Color3(1, 0, 0);

      sceneData.lights = [spot1, spot2];

      if (showHelpers) {
      }
    }

    sceneData.lights.forEach((obj) => {
      app.root.addChild(obj);
    });

    if (prevLights && prevLights !== undefined && prevLights !== lights) {
      if (sceneData.mesh && sceneData.mesh.render) {
        sceneData.mesh.render.meshInstances[0].material = loadingMaterial;
      }
      compile(ctx);
    }
  }, [
    app,
    sceneData,
    prevLights,
    lights,
    compile,
    ctx,
    previousShowHelpers,
    showHelpers,
    loadingMaterial,
  ]);

  useEffect(() => {
    let entity = new pc.Entity();

    const material =
      sceneData.mesh && sceneData.mesh.render
        ? sceneData.mesh.render.meshInstances[0].material
        : loadingMaterial;

    if (previewObject === 'torus') {
      const mesh = pc.createTorus(app.graphicsDevice, {
        segments: 60,
        sides: 32,
      });
      const meshInstance = new pc.MeshInstance(mesh, material);
      entity.addComponent('render', {
        meshInstances: [meshInstance],
      });
    } else if (previewObject === 'plane') {
      const mesh = pc.createPlane(app.graphicsDevice, {
        widthSegments: 60,
        lengthSegments: 60,
      });
      const meshInstance = new pc.MeshInstance(mesh, material);
      entity.addComponent('render', {
        meshInstances: [meshInstance],
      });
      entity.rotate(90, 0, 0);
    } else if (previewObject === 'cube') {
      const mesh = pc.createBox(app.graphicsDevice, {
        widthSegments: 60,
        heightSegments: 60,
      });
      const meshInstance = new pc.MeshInstance(mesh, material);
      entity.addComponent('render', {
        meshInstances: [meshInstance],
      });
    } else if (previewObject === 'sphere') {
      const mesh = pc.createSphere(app.graphicsDevice, {
        latitudeBands: 128,
        longitudeBands: 128,
      });
      const meshInstance = new pc.MeshInstance(mesh, material);
      entity.addComponent('render', {
        meshInstances: [meshInstance],
      });
    } else {
      throw new Error('fffffff');
    }

    if (sceneData.mesh && sceneData.mesh.render) {
      const origMat = sceneData.mesh.render.meshInstances[0].material;
      entity.render!.material = origMat;
    } else {
      entity.render!.material = loadingMaterial;
    }

    if (sceneData.mesh) {
      sceneData.mesh.destroy();
    }
    app.root.addChild(entity);
    sceneData.mesh = entity;
    // @ts-ignore
    window.mesh = entity;
  }, [app, previewObject, sceneData, loadingMaterial, camera]);

  const hasSetctx = useRef(false);
  const previousBg = usePrevious(bg);
  const previousTextures = usePrevious(textures);
  useEffect(() => {
    if (!textures || (textures === previousTextures && bg === previousBg)) {
      return;
    }
    const newBg = bg ? (textures[bg] as pc.Asset).resources : null;
    app.scene.setSkybox(newBg as pc.Texture[]);

    if (!hasSetctx.current) {
      hasSetctx.current = true;
      setCtx(ctx);
    }
  }, [
    bg,
    previousBg,
    sceneData,
    previewObject,
    textures,
    previousTextures,
    app,
    ctx,
    setCtx,
  ]);

  useEffect(() => {
    if (!canvas) {
      return;
    }
    canvas.width = width;
    canvas.height = height;
    app.resizeCanvas(width, height);
  }, [app, canvas, width, height]);

  useEffect(() => {
    if (!compileResult?.fragmentResult || !app?.graphicsDevice) {
      return;
    }
    const { graph } = compileResult;

    const pbrName = `component_playcanvas_${id()}`;
    log('🛠 Re-creating Playcanvas material', {
      pbrName,
      compileResult,
    });

    // Get runtime data properties to set on new shader
    const graphProperties = collectInitialEvaluatedGraphProperties(
      playengine,
      graph,
      defaultPropertySetting.bind(null, app)
    );

    setGlResult({
      fragError: null,
      vertError: null,
      programError: null,
    });

    const shaderMaterial = new pc.StandardMaterial();

    const newProperties = {
      ...physicalDefaultProperties,
      ...graphProperties,
      opacity: 1,
      userId: 'shaderfrog',
    };
    log('PlayCanvasEngine material props:', newProperties);
    Object.assign(shaderMaterial, newProperties);

    hackShaderDefinition = (info) => {
      log('Hacking the shader definition!', info);
      if (info.userMaterialId === 'shaderfrog') {
        info.definition.fshader =
          '#version 300 es\n' + compileResult.fragmentResult;
        info.definition.vshader =
          '#version 300 es\n' + compileResult.vertexResult;
      }
    };

    shaderMaterial.chunks[RUNTIME_CHUNK_HACK_NAME] = `${Math.random()}`;

    shaderMaterial.update();

    if (sceneData.mesh) {
      const mis = sceneData?.mesh?.render?.meshInstances || [];
      if (mis.length !== 1) {
        console.error('Too many mesh instances!', mis);
        throw new Error('Too many mesh instances!');
      }
      mis[0].material = shaderMaterial;
      log('created new materialId:', shaderMaterial.id);
    } else {
      console.warn('No mesh to assign the material to!');
    }
  }, [setGlResult, compileResult, sceneData, app, textures]);

  return (
    <>
      <div className={styles.sceneControls}>
        <div className={styles.controlGrid}>
          <div>
            <label htmlFor="Lightingsfs" className="label noselect">
              <span>Lighting</span>
            </label>
          </div>
          <div>
            <select
              id="Lightingsfs"
              className="select"
              onChange={(event) => {
                setLights(event.target.value);
              }}
              value={lights}
            >
              <option value="point">Single Point Light</option>
              <option value="3point">Multiple Point Lights</option>
              {/* <option value="spot">Spot Lights</option> */}
            </select>
          </div>

          <div className="grid span2">
            <div className={styles.controlGrid}>
              <div>
                <input
                  className="checkbox"
                  id="shp"
                  type="checkbox"
                  checked={showHelpers}
                  onChange={(event) => setShowHelpers(event?.target.checked)}
                />
              </div>
              <div>
                <label className="label noselect" htmlFor="shp">
                  <span>Lighting Helpers</span>
                </label>
              </div>
            </div>
            <div className={styles.controlGrid}>
              <div>
                <input
                  className="checkbox"
                  id="sha"
                  type="checkbox"
                  checked={animatedLights}
                  onChange={(event) => setAnimatedLights(event?.target.checked)}
                />
              </div>
              <div>
                <label className="label noselect" htmlFor="sha">
                  <span>Animate</span>
                </label>
              </div>
            </div>
          </div>

          <div>
            <label htmlFor="Modelsfs" className="label noselect">
              <span>Model</span>
            </label>
          </div>
          <div>
            <select
              id="Modelsfs"
              className="select"
              onChange={(event) => {
                setPreviewObject(event.target.value);
              }}
              value={previewObject}
            >
              <option value="sphere">Sphere</option>
              <option value="cube">Cube</option>
              <option value="plane">Plane</option>
              <option value="torus">Torus</option>
            </select>
          </div>

          <div>
            <label htmlFor="Backgroundsfs" className="label noselect">
              <span>Background</span>
            </label>
          </div>
          <div>
            <select
              id="Backgroundsfs"
              className="select"
              onChange={(event) => {
                setBg(
                  event.target.value === 'none' ? null : event.target.value
                );
              }}
              value={bg ? bg : 'none'}
            >
              <option value="none">None</option>
              <option value="cityCourtYard">City Court Yard</option>
              <option value="warehouseEnvTexture">Horrible Lord?</option>
            </select>
          </div>
        </div>
      </div>

      <div ref={pcDomRef} className={styles.sceneContainer}></div>
    </>
  );
};

export default PlayCanvasComponent;
